# Camada-Limite {#camada}

Já é um clichê de engenharia dizer que as Equações de Navier-Stokes (cf. Cap. \@ref(navier)) são complicadas. Vamos repetir aqui a componente na direção $i$:

$$
\rho \frac{\mathrm{d} V_i}{\mathrm{d}t} = -\frac{\partial P}{\partial x_i} + \rho g_i + \mu \nabla^2 V_i
$$

Neste capítulo, para facilitar a discussão, vamos desconsiderar os efeitos gravitacionais por serem menos importantes que os outros, e vamos considerar escoamento permanente bidimensional incompressível - por serem as situações típicas que queremos analisar (depois vamos explicar por quê). Vamos chamar as componentes da velocidade de $(u,v)$ nas direções respectivas $(x,y)$. As equações de conservação da massa e quantidade de movimento ficam então:

$$
\frac{\partial u}{\partial x} + \frac{\partial v}{\partial y} = 0
$$

$$
u\frac{\partial u}{\partial x} + v\frac{\partial u}{\partial y} = -\frac{1}{\rho}\frac{\partial P}{\partial x} + \nu\left(\frac{\partial^2 u }{\partial x^2} + \frac{\partial^2 u }{\partial y^2}\right)
$$

$$
u\frac{\partial v}{\partial x} + v\frac{\partial v}{\partial y} = -\frac{1}{\rho}\frac{\partial P}{\partial y} + \nu\left(\frac{\partial^2 v }{\partial x^2} + \frac{\partial^2 v }{\partial y^2}\right)
$$

Estas três equações de escoamento incompressível devem ser resolvidas para a tupla $(u,v,P)$. O que as torna tão difíceis? Alguns pontos:

- As equações não são separáveis
- Os termos de inércia são não-lineares
- Os termos viscosos são elípticos, o que requer condições de contorno a jusante do escoamento; isto aumenta o tempo computacional [@bib:kundu01-fluid-mechan] e impede um simples procedimento de marcha, que agora precisa ser iterado para convergir as condições de contorno a jusante.

## Sucesso da teoria de camada-limite

A grande sacada da teoria de camada-limite é que, para alguns problemas eminemente *práticos* [@bib:kundu01-fluid-mechan], nem todos os termos importam.

Nas minhas aulas de Transferência de Calor, quando começamos a estudar o assunto de convecção, eu sempre recomendo a meus alunos que examinem as tabelas de fluidos no final dos livros para ter uma noção de algumas propriedades. Um exame rápido mostra que, para a viscosidade cinemática $\nu$ à temperatura ambiente, existe quase uma separação binária: ar, água, fluidos refrigerantes, gases de combustão etc, que possuem viscosidade da ordem de alguns cm$^2$/s, e óleos lubrificantes e glicerinas, que possuem viscosidade mil vezes maior.
Para esse último caso, o número de Reynolds baseado em algum comprimento característico $L$ e alguma velocidade característica $V$:

$$
\mathrm{Re} = \frac{UL}{\nu}
$$

vai ser baixo, e a teoria apresentada neste capítulo tem pouca validade.

Porém, quando $\mathrm{Re}$ é alto, no escoamento de um fluido pouco viscoso ao redor de um corpo sólido - ou seja, escoamento de água ao redor de tubos em um trocador de calor, ou de ar ao redor de uma asa de avião em velocidades bem menores que a velocidade do som - coisas curiosas acontecem. A teoria de camada-limite prescreve que os efeitos viscosos só são não-deprezíveis em uma camada *muito fina* ao redor do corpo sólido (da ordem de alguns centímetros para um corpo de alguns metros de comprimento). Usar a equação de Euler (cf. Cap. \@ref(euler)) fora da camada-limite, "infinitamente longe da superfície sólida,  para simular o escoamento produz resultados compatíves com experimentos, não importa a viscosidade do fluido (desde que esteja realmente fora da camada limite). Assumir uma camada-limite fina, onde junto à parede o fluido está aderente à superfície (não-deslizamento) não importa a viscosidade, bate com os experimentos [@bib:kundu01-fluid-mechan].

Atualmente, podemos pensar no sucesso da teoria de camada-limite como um sucesso computacional. A simulação do escoamento em geometrias mais complexas, de trocadores imitando a natureza por exemplo (cf. Cap. \@ref(tubulacoes)), é simplificada porque o domínio de computação é dividido em dois: um pequeno, com poucos nós, onde é preciso levar muitos termos em conta, e um grande domínio externo onde poucos termos importam.

## Simplificações de Camada-Limite

Mas que simplificações são essas? Vamos chamar de $x$ o eixo paralelo originalmente ao escoamento ao redor de um corpo. A velocidade $v$ é então zero fora da camada-limite, e tem um valor pequeno dentro da camada-limite para satisfazer a conservação da massa, já que o fato de que $u$ varia de zero na superfície até $V$ fora da camada-limite implica em variações de $u$. Porém, os gradientes na direção $x$ são bem menores que na direção $y$ (onde é preciso haver variações finitas numa distância pequena).

A equação de conservação da massa então não é alterada, pois $u$ não pode ser desprezada e nem gradientes na direção $y$. Na conservação da quantidade de movimento em $x$, o gradiente de segunda ordem pode ser desprezado:

$$
u\frac{\partial u}{\partial x} + v\frac{\partial u}{\partial y} = -\frac{1}{\rho}\frac{\partial P}{\partial x} + \nu\left( \frac{\partial^2 u }{\partial y^2}\right)
$$

Por que o gradiente em $x$ no lado esquerdo não pode ser desprezado? Porque ele está sendo transportado pela própria velocidade $u$, que é a maior componente de velocidade, ao passo que a derivada segunda está multiplicada pela viscosidade, que é suposta pequena. Isso automaticamente elimina a necessidade de uma segunda condição de contorno de $u$ na direção $x$.

E a conservação em $y$? Todos os termos da ordem de $v$ são muito pequenos. O primeiro gradiente do lado esquero está multiplicado por $u$, que é grande, mas é um gradiente em $x$, que é pequeno. O resultado prático é:

$$
\frac{\partial P}{\partial y} = 0
$$

ou seja, a pressão é imposta pelo escoamento invíscido (que pode ser resolvido separadamente) na camada-limite.

Pode-se mostrar que essa explicação intuitiva dada acima ("quais termos somem e quais não") pode ser tornada exata quando se adimensionaliza as Equações de Navier-Stokes e se toma o limite $\mathrm{Re} \to \infty$.

Diferentes soluções existem para as equações simplificadas de camada-limite [@bib:bejan95-convec-heat-trans]. Como na maior parte das situações de engenharia, devemos aliar soluções analíticas exatas (que fornecem um entendimento matemático e podem ser usadas para comparar e validar experimentos e algoritmos numéricos), numéricas (que são confiáveis depois de comparadas com experimentos e soluções simplificadas) e experimentais para o entendimento completo do problema e projeto final de sistemas de engenharia.

