# Arrasto e Sustentação {#arrasto}

A corrida tem se tornado um esporte bastante popular. Qualquer corredor percebe que, ao correr em regiões onde o vento é muito forte, você sente nas suas pernas a energia adicional necessária para superar essa força. Que força é essa?

A força sofrida por um corpo em velocidade relativa a um escoamento de fluido, na direção do escoamento, é chamada de *força de arrasto*.

Dependendo da orientação do corpo, a força de arrasto vai ter duas componentes:

- o arrasto viscoso
- o arrasto de pressão

Por exemplo, uma placa plana paralela ao escoamento vai sentir apenas arrasto viscoso, pois não há gradientes de pressão que gerem uma força resultante. Em contraste, uma placa colocada como anteparo perpendicular a um escoamento vai sentir apenas arrasto de pressão, pois em nenhuma parte o escoamento é tangencial (cisalhante) à placa. Em inclinações intermediárias, o arrasto vai ter uma participação das duas forças presentes no escoamento.

Parte do grande sucesso da teoria de camada-limite (cf. Cap. \@ref(camada)) é a explicação do arrasto dentro de uma perspectiva teórica [@bib:white6]. A teoria de camada-limite mostra que, quando um escoamento com alto número de Reynolds encontra um corpo, a camada de fluido
adjacente ao corpo fica aderida a este (camada de não-deslizamento), enquanto que suficientemente longe do corpo não existem forças viscosas. Na região intermediária os gradientes de velocidade induzem tensões viscosas que geram forças. Porém, esta teoria também explica o papel da pressão: se um corpo *rombudo* altera as linhas de corrente (por exemplo, escoamento de ar ao redor de um tubo), a velocidade vai ser alterada simplesmente pela Conservação da Massa (cf. Cap. \@ref(cinematica)), o que vai gerar um gradiente de pressão externo que atua sobre a camada-limite pela Equação de Bernoulli (cf. Cap. \@ref(euler)). Podem haver situações onde esse gradiente de pressão *adverso* age contra o movimento inercial, o que vai retardando o movimento até inverter o sentido de escoamento da camada-limite, gerando vórtices e uma região de baixa pressão. Isto gera uma esteira na parte de trás do corpo, aumentando grandemente o arrasto (de pressão).

O avanço no entendimento do arrasto e na fabricação de chapas metálicas possibitou carros cada vez mais *carenados*, alongados, para retardar ao máximo a formação da esteira e o desprendimento da camada-limite, reduzindo o arrasto de pressão (embora isso aumente o arrasto de atrito pelo aumento da área superficial, e portanto existe um carenamento ótimo que reduz o arrasto total [@CengelMFL]). É interessante observar que essa otimização é mais relevante com o passar do tempo pelo aumento das velocidades atingidas e do preço de combustível [@CengelMFL]. Além disso, esse tipo de problema de projeto ilustra uma situação típica de engenharia: a forma deve ser otimizada fluidodinamicamente, mas é preciso levar em conta aspectos práticos como a instalação dos espelhos, o espaço de porta-malas e o conforto dos passageiros [@CengelMFL]. 

Outra situação onde o arrasto exerce papel muito importante é na aviação. Um carro precisa vencer o atrito com o solo também, mas um avião só gasta combustível viajando em velocidade constante para vencer o arrasto. Grande pesquisa é feita para minimizar o arrasto enquanto maximiza a força de *sustentação* - perpendicular ao escoamento, no sentido contrário à gravidade. Também essa força tem componentes de atrito viscoso e de pressão. Porém, como o avião faz para "frear"? Um carro aumenta o atrito sobre o solo, ao passo que um avião altera o ângulo de ataque (entre o escoamento e a *corda* da asa, uma linha que conecta os bordos de ataque - onde o escoamento encontra a asa - e de fuga - onde não existe mais asa). 

A formação da esteira e de vórtices dificulta enormemente a modelagem teórica desse escoamento, de maneira que grande parte do desenvolvimento nessa área tem sido com experimentos (determinando por exemplos tratamentos de superfície que retardam a formação de esteira) e simulações numéricas. As forças de arrasto e sustentação são adimensionalizadas em termos do produto da pressão dinâmica $\frac{1}{2}\rho V^2$ por alguma área característica do corpo, que deve ser bem definida. Os *coeficientes de arrasto e sustentação* assim definidos vão depender primariamente do número de Reynolds. Há que se ter cuidado nessas definições, por que um baixo coeficiente de arrasto não significa uma força baixa, se simplesmente a área característica for muito grande. Outro exemplo de como essas definições importam: a força de arrasto sobre um ciclista é reduzido quando ele se inclina para a frente, pois isso altera a forma do escoamento, tornando-o mais paralelo ao escoamento (e portanto diminui o coeficiente de arrasto de pressão) *e ao mesmo tempo* diminui a área frontal [@CengelMFL]. Como última observação, veja que a força de arrasto, para um coeficiente de arrasto constante, é proporcional ao quadrado da velocidade (dirija devagar).

Assim como a minimização do arrasto, a maximização da sustentação é outra área de pesquisa ativa. Todos os ângulos e dimensões de uma asa de avião são altamente otimizados com procedimentos numéricos e experimentais, e alguns fenômenos são observados. O primeiro é a ocorrência do *estol*: uma queda brusca da relação sustentação/arrasto dependendo das condições de escoamento (como ângulo de ataque muito alto ou velocidades muito baixas). O escoamento é instável e a queda de sustentação infelizmente já levou a muitos acidentes.

Além da aviação, outra área onde o estol é bastante relevante é no estudo de turbo-compressores para sobrealimentação de motores. As pás de um equipamento deste tipo têm a forma de aerofólios, justamente para maximizar a sustentação (isto é, maximizando a força normal que de fato adiciona energia ao fluido sendo comprimido) enquando minimiza a força de atrito (que retira energia do fluido). Todos os mapas de turbo-compressores incluem uma região de estol, onde a vazão é muito baixa e não há sustentação suficiente, e o atrito em excesso pode danificar o compressor [@bib:Brunetti2012a]. Como a popularização de "carros turbo", esta deve ser uma área importante de desenvolvimento, deixando esses equipamentos mais confiáveis para reduzir o custo de operação. Será possível projetar compressores que funcionam de maneira adequada até em vazões baixas, ampliando a faixa na qual o torque é aumentado?


