# Escoamento Compressível {#compressivel}

Tubos capilares são usados em sistemas de refrigeração por compressão mecânica de vapor de baixa capacidade (até o nível de um ar-condicionado residencial), consistindo em tubos de cerca de 0,5-2 mm de diâmetro interno e cerca de 5 m de comprimento [@bib:DELARA202037]. O seu propósito é reduzir a pressão do fluido refrigerante entre o condensador e o evaporador, e ao fazer isso controlar a vazão de fluido fornecida pelo compressor para atingir o valor de vazão compatível com a capacidade de refrigeração desejada.

Ao simular e projetar um tubo capilar, ocorre um fenômeno interessante: se você considera a pressão de condensação como fixa, quando maior o tubo capilar, maior a queda de pressão (cf. Cap. \@ref(tubulacoes)), e portanto maior a vazão que pode passar pelo tubo (pois maior o potencial para escoaamento) - mas só até certo ponto. A partir de um certo ponto, aumentar o tubo capilar para reduzir ainda mais a pressão na saída não tem efeito na vazão, e o escoamento fica *blocado*. A blocagem limita a eficiência de sistemas de refrigeração [@bib:stoecker]. Por que isso acontece?

Outro exemplo onde a eficiência de um sistema é limitada pela vazão de fluido: motores de combustão interna. Quanto mais ar é possível ao motor succionar, mais combustível pode ser queimado sem aumentar a taxa de emissões de poluentes [@bib:Heywood1988], e portanto mais energia é liberada pelo motor. A grande restrição para o escoamento de ar é a válvula de admissão, onde o ar encontra a menor área de passagem (principalmente quando ela não está totalmente aberta), e portanto é ali que a velocidade é a maior. Experimentos mostram que, se essa velocidade é *alta demais* (o que ocorre quando a válvula é sub-dimensionada), a quantidade de ar que entra no motor na verdade diminui. Por que isso acontece?

## Velocidades sônicas

Em ambos os casos acima, a velocidade de referência no sistema, geralmente a máxima velocidade, ficou muito próxima da *velocidade do som*. A velocidade do som é a velocidade de uma onda de pressão de magnitude infinitesimal que se propaga em um fluido estático [@bib:cengel]. Em um fluido parado com velocidade $V = 0$ e propriedades ($P,\rho,h$), à medida que a onda passa o fluido se acelera a $\mathrm{d}V \ne 0$ e as propriedades são perturbadas. Esse processo é geralmente modelado como isentrópico (adiabático e reversível). Logo, a exigência de conservação da massa, energia e entropia à medida que o fluido se desloca pela onda requer que a velocidade do som satisfaça:

$$
c^2 = \left(\frac{\partial P}{\partial \rho}\right)_s
$$

O que, usando propriedades termodinâmicas, pode ser re-escrito como:

$$
c^2 = k\left(\frac{\partial P}{\partial \rho}\right)_T
$$
onde $k$ é a razão de calores específicos.

*Especificamente*, para gases ideais

$$
c = \sqrt{kRT}
$$
onde $R$ é a constante do gás. A velocidade do som pode ser calculada para outros fluidos com base na sua equação de estado, e em geral depende da pressão. Por exemplo:

``` {python}
from CoolProp.CoolProp import PropsSI
PropsSI("A","T",300,"P",1e5,"R134a")
```

Seja um fluido escoando em um ponto com velocidade $V$, e com temperatura $T$ e pressão $P$, de maneira que a sua velocidade do som seja $c$. O número de Mach do escoamento é:

$$
\mathrm{Ma} = \frac{V}{c}
$$

Nos exemplos anteriores, é o número de Mach que determina as restrições. O escoamento se torna blocado em tubos capilares quando Mach se torna unitário, e reduções na capacidade de enchimento de ar de motores ocorrem quando $\mathrm{Ma} > \frac{1}{2}$ [@bib:Brunetti2012a]. O escoamento se torna *compressível*.

## Modificações de densidade

Considere um fluido escoando por uma tubulação adiabática em regime permanente. A viscosidade é baixa o suficiente de maneira que não há dissipação viscosa (o trabalho das forças viscosas é desprezível). Os efeitos gravitacionais também são desprezíveis. Então, à medida que o fluido escoa, a soma

$$
h + \frac{V^2}{2} = h_0
$$
é constante, onde $h_0$ é a entalpia de estagnação. Em muitas aplicações de engenharia, a velocidade dos fluidos costuma ser da ordem de 10 m/s; mas em algumas situações muita específicas, como os tubos capilares e alimentação de motores, essas velocidades são cerca de 10x maior. Portanto, a energia cinética é importante, e é convertida em entalpia em alguns processos, alterando a temperatura e com isso todas as outras propriedades. 

Por exemplo, no escoamento de tubos capilares, a velocidade aumenta porque o fluido entra como líquido saturado e a queda de pressão induzida pelo fator de atrito vaporiza parte do líquido, e o vapor, sendo menos denso, acelera mais. Se a velocidade aumenta, a entalpia precisa reduzir de acordo com a equação acima, e o vapor formado vai ficando cada vez mais frio.

Sejam 1 e 2 duas seções distintas do tubo capilar de diâmetro $D$ (resultando numa área de escoamento $A$), separadas por uma distância $\Delta L$. A vazão que escoa no tubo $\dot{m}$ é constante. A Segunda Lei de Newton estabelece:

$$
(P _1-P _2) - f _m \frac{\Delta L}{D}\frac{\rho_m V _m^2}{2} = \frac{\dot{m}}{A}\left(V _2-V _1\right)
$$

Na simulação de tubos capilares, é comum resolver essa equação para dimensionar o comprimento, e achar que ele deu um valor negativo. O que acontece? Inspecionando a equação acima, isso pode acontecer quando a variação de velocidade ultrapassa um certo valor que seria permitido pela diferença de pressão. Do início deste texto, a velocidade que "amarra" as variações de pressão e densidade é a velocidade do som; logo, quando o escoamento se torna sônico, as variações de propriedades se tornam "impossíveis".

Isso pode ser analisado do ponto de vista da Segunda Lei da Termodinâmica: se o tubo é adiabático, sua entropia pode no mínimo permanecer constante, se o processo for reservível. O que acontece na prática é um conflito: o atrito gera entropia, e o abaixamento da temperatura pela conservação da entalpia de estagnação tende a diminui-la. Esse segundo efeito nunca pode ultrapassar o primeiro, e é isto que bloca o escoamento: quando "a entropia tenta diminuir", o tubo responde restrigindo a vazão, criando uma restrição ao escoamento maior.  A velocidade do som, se ocorrer, sempre ocorre no final do tubo, de maneira que o fluido não possa ser acelerado além disso.

Como acelerar um fluido além da velocidade do som, por exemplo? Em turbinas a gás de aviação, o fluido é acelerado na saída com velocidades altas para gerar uma força de propulsão na aeronave (já que não há rodas). Isso é feito com *bocais supersônicos*, que são na verdade *divergentes*. Considere um escoamento isentrópico de um gás ideal num bocal de seção variável. A vazão mássica é constante:

$$
\dot{m} = \rho V A
$$

A equação de Bernoulli é aplicável, bem como a definição de velocidade do som. Isso resulta na relação:

$$
\frac{\mathrm{d}V}{V} = \frac{\mathrm{d}A}{A}\frac{1}{\mathrm{Ma}^2-1}
$$

Logo, em escoamento supersônico, o escoamento acelera no sentido do aumento de área. Para evitar uma singularidade em $\mathrm{Ma}=1$, a área deve ser mínima nessa condição (uma inspeção mostra que uma seção abaulada não funciona, pois se o escoamento subsônico começa em um difusor, a sua velocidade vai diminuir até a área máxima). Em um tubo capilar, não é a área que muda, e sim a densidade, mas o efeito é o mesmo - o escoamento só consegue acelerar até certo ponto. Isto costuma confundir muitos engenheiros e engenheiras, mas como visto, estas restrições têm efeito prático sobre a eficiência de sistemas.

E isso conclui este livro.
